### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by visch** [AutoIDM/tap-clickup#6]
- [x] CI
- [x] All Streams
- [x] Discovery
- [x] Catalog ingestion
- [x] Rate Limiting
- [x] Error Handling
- [x] Testing with actual data
- [x] Be sure documentation is clear (Should happen along the way)
- [x] Add MIT License
- [ ] Release 1.0.0 to PyPi 
- [x] Submit to Stitch
- [x] Submit to Meltano Hub

Order will jump around, and there will be individual issues for most units of work. This is the higher level task to be sure we get everything done!

**Comment by visch** [comment]
- [ ] Full code review

**Comment by visch** [comment]
Not going to release 1.0.0 until we feel like it later. This works as it is, if we need some more stability in the api later we can circle back to this.
